### PR TITLE
Russian Translation Update

### PR DESCRIPTION
**Pull request by Alter0ne**
Hi! I made the necessary changes to the Russian translation. Now it fully worked in 0.103, 0.104 versions of puNES. Please check it.

### CODE REVIEW

**Comment by punesemu** [comment]
Hi Alter0ne and many thx for your contribution. This weekend I'll take a look at the patch and if there's no problem I'll marge it. I'm working on some new features to add in the near future and I hope you can help me to translate these when the time comes.

**Comment by punesemu** [comment]
Hi Alter0Ne, I bother you to ask you a favor, I would like to release version 0.104 of the emulator and I would like it to contain a complete translation of the GUI. Compared to the translation you've already done, there are a dozen more strings, the options for the new rewind function. Would you mind updating it? This is the updated ts file [ru_RU.ts](https://www.dropbox.com/s/vzbw5bqbnq84izf/ru_RU.ts?dl=0). If you can't, it doesn't matter.

**Comment by Alter0ne** [comment]
Hi, punesemu. I will do it today.

**Comment by Alter0ne** [comment]
Done. I translated "Rewind minutes" as "Rewind Duration".
[https://www.dropbox.com/s/e8rzx1xg2cqtmo8/ru_RU.ts?dl=0](ru_RU.ts)
[https://www.dropbox.com/s/ew5j9ws8xh6utif/ru_RU.qm?dl=0](ru_RU.qm)

**Comment by punesemu** [comment]
Thx, I owe you a beer.

**Comment by Alter0ne** [comment]
Hello, FHorse. These are my updated translations for 0.105 version:
[ru_RU.ts](https://www.dropbox.com/s/e8rzx1xg2cqtmo8/ru_RU.ts?dl=0)
[ru_RU.qm](https://www.dropbox.com/s/ew5j9ws8xh6utif/ru_RU.qm?dl=0)
[qt_ru.ts](https://www.dropbox.com/s/5lok8r72iwh1sb4/qt_ru.ts?dl=0)
[qt_ru.qm](https://www.dropbox.com/s/kh6lx7djk0h9kxr/qt_ru.qm?dl=0)

**Comment by punesemu** [comment]
Hi Alter0ne, thx for the update. I wanted to ask you why don't you sign up for Crowdin? It would be easier to manage the translation. If you already have a github occunt sign up is very simple. This is the link for [puNES on Crowdin](https://crowdin.com/project/punes).

**Comment by Alter0ne** [comment]
Thanks for the link. I will update the translation there.

**Pull request merged**
