### PR TITLE
Updated frenc language by Benjamin Siskoo

### PR DESCRIPTION
**Pull request by BenjaminSiskoo**

### CODE REVIEW

**Comment by punesemu** [comment]
As usual, thank you. :beer:

**Comment by BenjaminSiskoo** [comment]
like usual, my pleasure :) New release for the new year ?

**Comment by punesemu** [comment]
My intention was to release it tomorrow, but with today's commits I prefer to wait a few days to be sure I haven't introduced any new bugs.

**Comment by BenjaminSiskoo** [comment]
ok :) I translated the changelog ^^

**Comment by punesemu** [comment]
Benjamin, "** Pour appliquer ce changement, un redémarrage est nécessaire **" can it be shortened a bit?

**Comment by BenjaminSiskoo** [comment]
Yes "Un redémarrage est nécessaire suite au changement". Or "Ce changement nécessite un redémarrage".

**Comment by punesemu** [comment]
"Ce changement nécessite un redémarrage" :+1:

**Pull request merged**
