### PR TITLE
Initial support of CMake build system

### PR DESCRIPTION
**Pull request by winterheart**
Implementing initial support of CMake build system (#234). Some things of Autotools project had to be rewrote in order to fit cmake/qt5 build environment: changed file patterns for UI, MOC and RCC files generations, since cmake's AUTOMOC/AUTOUI/AUTORCC generates files in that way.
Untied xdelta3 project from autoconf (since there only one file required from xdelta3, there can be do more).
Added GitHub Actions file for compilation with cmake on Linux.

Overall, there are some things to do:
* Get worked Windows build with cmake (D3D9 support)
* Properly handle with bundled precompiled libraries on Windows (I have plans do it with vcpkg, through I never worked with it in mingw/msys2 environment)
* Check all optional features

I'm estimate that there about 70-80 % of completed migration done. I definitely finish things from TODO list, but now I just want sync my working with main branch.

### CODE REVIEW

**Comment by punesemu** [comment]
Many thx winterheart, this is a fantastic contribution. Once it is stabilized I will have to see how to add the option for QT6 support, the sources are already compatible.

**Comment by winterheart** [comment]
> Once it is stabilized I will have to see how to add the option for QT6 support, the sources are already compatible.

Actually, I think there no much to do. I've discovered that cmake projects which compatible with Qt 5.15, are ready to go to Qt6 world, so I made some adjustments to ensure transition will be smooth.

**Comment by punesemu** [comment]
When I run autogen.sh under Windows I get this warning that bothers me:
```
src/gui/Makefile.am: 112: warning: variable 'QM_SOURCES' is defined but no program or
src/gui/Makefile.am: 112: library has 'QM' as canonical name (possible typo)
```
I think I'll rename 'QM_SOURCES' to 'QM_FILES'.

**Comment by punesemu** [comment]
Finally I managed to get the emulator compiled with cmake under OpenBSD. Since I am new to cmake they may need to be checked by a more experienced eye. If you have some time, could you take a look?
[punes-cmake-openbsd.patch](https://gist.github.com/punesemu/823502d381db771dae9dd562426fbae1)

**Comment by winterheart** [comment]
FindSndio.cmake better take from here https://github.com/libsndfile/libsndfile/blob/master/cmake/FindSndio.cmake. Other parts looking good!

**Comment by punesemu** [comment]
Many thx https://github.com/punesemu/puNES/commit/c566d10b37c1c725323c46cbfa0d9347cf49cec2.

**Comment by punesemu** [comment]
Finally I was able to compile the windows executable also from my gentoo using the precompiled libraries I used with the autotools.
[punes_mingw32_crosscompile-patch](https://gist.github.com/punesemu/475952a07298a9fab2e446d4df54e620#file-punes_mingw32_crosscompile-patch)

**Pull request merged**
