### PR TITLE
Fixed typos (French language)...

### PR DESCRIPTION
**Pull request by BenjaminSiskoo**

### CODE REVIEW

**Comment by punesemu** [comment]
Don't correct `&apos;` it's not an error. It's the QT Linguist software (what I use to manage the various translations) that transforms accents and other signs into the corresponding [HTML Predefined Character Entities.](http://www.madore.org/~david/computers/unicode/htmlent.html). In this case I will manually apply the fix you have made, I won't do the merge since I also managed the various `type="unfinished"` by eliminating them. Thx anyway for the support.

**Comment by BenjaminSiskoo** [comment]
I fixed lot typos, I'll dol the source and will fix again :)

**Comment by punesemu** [comment]
Is this correct `<translation>Bordures noires en mode Fenêtré</translation>`?
I see you fixed a similar sentence `<translation>Bordures noir en mode Plein Ecran</translation>` changing `noires` with `nois`.

**Comment by BenjaminSiskoo** [comment]
Close this commit, I'll get the last code, and going to fix it :)

**Comment by punesemu** [comment]
Ok :)

**Pull request closed without merging**
