### PR TITLE
Fix infringement issues with Nes_controller.svg

### PR DESCRIPTION
**Pull request by RokkumanX**
This should fix all the issues addressed in #63 

The design on this NES controller is pretty unique now:

1.    Altered background color to a lighter grey
2.    Changed font to Tahoma and font color to cyan
3.    Changed color of the B & A buttons to plain blue
4.    The puNES logo is used instead of the Nintendo logo

Infringement issues = 0

The cyan/blue colors are an homage to the blue bomber!

### CODE REVIEW

**Comment by RokkumanX** [comment]
Seems Tahoma is Windows exclusive also, I haven't found any universal OS font.

The .svg format isn't exactly easy to work with, but I think I have done all I can at this point with what I have.

If anyone have any further suggestions just feel free to post them here.

**Comment by RokkumanX** [comment]
This was the last commit on this at least from me, anyone can freely make changes if they are not happy with the result.

The result here is my interpretation of how the infringement issues could be resolved and it looks good on my end.

Again, it's anyone's game really. I've spent enough time on this as it is.

**Comment by punesemu** [comment]
Well done. I really like your work and I thank you for the time you spent with it. Now I'm working on another task but as soon as I complete it I will import the SVG into my tree.

**Comment by RokkumanX** [comment]
Thank you very much for your feedback, I hope everyone will be satisfied with it!

**Comment by punesemu** [comment]
input_Nes_Controller
Here's how it looks on my linux.

**Comment by RokkumanX** [comment]
Looks awesome!

**Comment by punesemu** [comment]
https://github.com/punesemu/puNES/commit/f326c4c9bf7df645e2b138fac23e626e7ca13156

**Pull request closed without merging**
