### PR TITLE
French translation by Benjamin Siskoo

### PR DESCRIPTION
**Pull request by BenjaminSiskoo**

### CODE REVIEW

**Comment by punesemu** [comment]
Many thx Benjamin Siskoo. :beers:

**Comment by BenjaminSiskoo** [comment]
You're welcome, thanks for this great emulator.

**Comment by punesemu** [comment]
I realized that the fr_FR.ts was not updated as some sentences were missing. I updated it. If you still want to help me, how about updating it? For convenience, you could use the Crowdin platform which offers convenient tools for translation. I have sent you an invitation email.

**Comment by BenjaminSiskoo** [comment]
It's not a problem to me to translate with notepad :)

**Comment by punesemu** [comment]
Great, but at least use Notepad++ :smile:

**Comment by BenjaminSiskoo** [comment]
yup notepadd++ :)is my friend for many years now ^^

**Comment by BenjaminSiskoo** [comment]
I'm translate the last version. I saw this : 
image

is it NES 2.0 or iNES 2.0 ?

**Comment by punesemu** [comment]
[NES 2.0](https://www.nesdev.org/wiki/NES_2.0).

**Pull request merged**
